// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7_brqaYda4tc6_jaR2gCJi1pPlUOPfhY',
    appId: '1:678458683520:android:3bb53688b6f516c3533665',
    messagingSenderId: '678458683520',
    projectId: 'reminder-app-b5225',
    databaseURL: 'https://reminder-app-b5225-default-rtdb.firebaseio.com',
    storageBucket: 'reminder-app-b5225.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCorz7VDWWV6nFFNJJvSOI06iUYc0mqCgY',
    appId: '1:678458683520:ios:dc1d91921835ff3a533665',
    messagingSenderId: '678458683520',
    projectId: 'reminder-app-b5225',
    databaseURL: 'https://reminder-app-b5225-default-rtdb.firebaseio.com',
    storageBucket: 'reminder-app-b5225.firebasestorage.app',
    iosBundleId: 'com.example.reminderApp',
  );
}
